import algroots


def test_public_api() -> None:
    expected = {
        "algsolve",
        "polysolve",
        "algebraize_system",
        "AlgebraicSystemRoots",
        "AlgebraizedSystem",
        "recognize_system_roots",
        "PolynomialSystemRoots",
        "RootDiagnostics",
        "RecognizedSystemRoot",
        "ExactCertificationError",
        "PolynomialSystemError",
        "PolynomialSystemInputError",
        "NotZeroDimensionalError",
        "ActionMatrixError",
        "HomotopySolveError",
        "ShapePositionError",
        "TriangularSolveError",
        "NumericalRootError",
        "SystemSolveLimitError",
        "RationalUnivariateError",
        "RationalUnivariateRepresentation",
        "RationalUnivariatePoint",
        "compute_rational_univariate_representation",
        "solve_zero_dimensional_system_with_rur",
        "solve_rur_representation",
        "solve_rur_points",
        "BorderBasisDiagnostics",
        "BorderBasisError",
        "BorderBasisResult",
        "compute_border_basis",
        "compute_border_basis_linear",
        "HomotopySystem",
        "SympyHomotopy",
        "PathTrackerOptions",
        "PathStep",
        "PathResult",
        "PathTrackingError",
        "PathStepError",
        "track_path",
        "CaptureRecaptureEstimate",
        "capture_recapture_estimate",
        "second_order_trace_test",
        "MonodromyLoop",
        "MonodromyPermutation",
        "MonodromyOrbitResult",
        "MonodromyRootInfo",
        "closed_additive_loop",
        "track_loop",
        "monodromy_permutation",
        "discover_monodromy_orbit",
        "__version__",
    }
    assert set(algroots.__all__) == expected
